name: Says hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run: echo "hola Crack"
      - name: Dime la fecha
        run: date
      - name: Carpetas directorio
        run: ls -l
