name: Says hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run: echo "hola Crack"
      - name: Say data actually
        run: data
      - name: list folders
        run: ls -l
